on: [push, pull_request]
name: Test
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: |
       RACE=1 make test
  static-check:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Static check
      run: |
       make install-static-check-tools
       make static-check
